create table TB_PUBLISHING_COMPANY (
    ID BIGINT NOT NULL,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT PUBLISHING_COMPANY_PK PRIMARY KEY (ID)
);

create sequence PUBLISHING_COMPANY_SEQ increment 1 start 1;