create table TB_COMIC_GNERE (
    COMIC_ID BIGINT NOT NULL,
    GNERE_ID BIGINT NOT NULL,
    CONSTRAINT COMIC_GNERE_PK PRIMARY KEY  (COMIC_ID,GNERE_ID),
    CONSTRAINT COMIC_GNERE_C_FK FOREIGN KEY(COMIC_ID) REFERENCES TB_COMIC(ID),
    CONSTRAINT COMIC_GNERE_G_FK FOREIGN KEY(GNERE_ID) REFERENCES TB_GNERE(ID)
);