create table TB_COMIC_WRITER (
    COMIC_ID BIGINT NOT NULL,
    WRITER_ID BIGINT NOT NULL,
    CONSTRAINT COMIC_WRITER_PK PRIMARY KEY  (COMIC_ID,WRITER_ID),
    CONSTRAINT COMIC_WRITER_C_FK FOREIGN KEY(COMIC_ID) REFERENCES TB_COMIC(ID),
    CONSTRAINT COMIC_WRITER_W_FK FOREIGN KEY(WRITER_ID) REFERENCES TB_WRITER(ID)
);